// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Volo.Abp.EntityFrameworkCore;
using hmt_energy_csharp.EntityFrameworkCore.Oracle;

#nullable disable

namespace hmtenergycsharp.OracleMigrations
{
    [DbContext(typeof(hmt_energy_csharpOracleDbContext))]
    [Migration("20230615064225_update_vesselinfo")]
    partial class updatevesselinfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.Oracle)
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hmt_energy_csharp.VesselInfos.VesselInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AsternDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLGHFOCACC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLGMDOCACC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRFCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRHFOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRHFOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRMDOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRMDOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRSFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BowDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Course")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGFCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGHFOCACC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGHFOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGHFOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGMDOCACC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGMDOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGMDOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGPower")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGSFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Depth")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DepthOffset")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Draft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("FCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("GroundSpeed")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("HFOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Heel")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MDOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEFCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEHFOCACC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEHFOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEHFOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEMDOCACC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEMDOCPerNm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEMDOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEPower")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MERpm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MESFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("PortDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Pressure")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("ReceiveDatetime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double?>("ResetDistanceGrd")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("ResetDistanceWat")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("SFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)");

                    b.Property<double?>("Slip")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("StarBoardDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Temperature")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Thrust")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Torque")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("TotalDistanceGrd")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("TotalDistanceWat")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Trim")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Visibility")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WaterSpeed")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WaveDirection")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WaveHeight")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Weather")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<DateTime?>("delete_time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("vesselinfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
