// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Volo.Abp.EntityFrameworkCore;
using hmt_energy_csharp.EntityFrameworkCore.Oracle;

#nullable disable

namespace hmtenergycsharp.OracleMigrations
{
    [DbContext(typeof(hmt_energy_csharpOracleDbContext))]
    [Migration("20230606084105_init_oracle")]
    partial class initoracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.Oracle)
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hmt_energy_csharp.VesselInfos.VesselInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AsternDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRHFOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRMDOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BLRSFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("BowDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Course")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGHFOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGMDOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DGSFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Depth")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("DepthOffset")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Draft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("GroundSpeed")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Heel")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEHFOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEMDOConsumption")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MEPower")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MERpm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MESFOC")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("PortDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Pressure")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("ReceiveDatetime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double?>("ResetDistanceGrd")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("ResetDistanceWat")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("Sid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double?>("StarBoardDraft")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Temperature")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Thrust")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Torque")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("TotalDistanceGrd")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("TotalDistanceWat")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Trim")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Visibility")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WaterSpeed")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WaveDirection")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WaveHeight")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Weather")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("create_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<DateTime?>("delete_time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double?>("slip")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime?>("update_time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("vesselinfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
